apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: tournaments
build:
  local:
    push: false
  artifacts:
    - image: tournaments/user
      context: .
      docker:
        dockerfile: user/Dockerfile
      sync:
        manual:
          - src: 'user/src/**/*.ts'
            dest: ./user
          - src: 'common/src/**/*.ts'
            dest: ./common
    - image: tournaments/tournament
      context: .
      docker:
        dockerfile: tournament/Dockerfile
      sync:
        manual:
          - src: 'tournament/src/**/*.ts'
            dest: ./tournament
          - src: 'common/src/**/*.ts'
            dest: ./common
    - image: tournaments/participation
      context: .
      docker:
        dockerfile: participation/Dockerfile
      sync:
        manual:
          - src: 'participation/src/**/*.ts'
            dest: ./participation
          - src: 'common/src/**/*.ts'
            dest: ./common
    - image: tournaments/organizer
      context: .
      docker:
        dockerfile: organizer/Dockerfile
      sync:
        manual:
          - src: 'organizer/src/**/*.ts'
            dest: ./organizer
          - src: 'common/src/**/*.ts'
            dest: ./common
    - image: tournaments/email
      context: .
      docker:
        dockerfile: email/Dockerfile
      sync:
        manual:
          - src: 'email/src/**/*.ts'
            dest: ./email
          - src: 'common/src/**/*.ts'
            dest: ./common
    - image: tournaments/query
      context: .
      docker:
        dockerfile: query/Dockerfile
      sync:
        manual:
          - src: 'query/src/**/*.ts'
            dest: ./query
          - src: 'common/src/**/*.ts'
            dest: ./common
manifests:
  rawYaml:
    - ./infra/k8s/*
